name: Build Windows
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - 'master'
      - 'release'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 480
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    strategy:
      fail-fast: false
      matrix:
        visualization: [ForestScene]
        os: [windows-2019]
        targetPlatform: [StandaloneWindows64, StandaloneWindows]
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        lfs: true
    
    - name: Cache
      uses: actions/cache@v3
      with:
          path: ./${{ matrix.visualization }}/Library
          key: ${{ matrix.visualization }}-${{ matrix.os }}-Library-${{ matrix.targetPlatform }}
          restore-keys: ${{ matrix.visualization }}-${{ matrix.os }}-Library-

    - name: Test
      shell: cmd
      run: |
        cd ForestScene
        dir /s
    
    - name: Build
      uses: game-ci/unity-builder@v2
      env:
        UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
        UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
      with:
        targetPlatform: ${{ matrix.targetPlatform }}      
        projectPath: ./${{ matrix.visualization }}
        buildsPath: ./${{ matrix.visualization }}/Build
        buildName: ${{ matrix.visualization }}

    - name: Test
      shell: cmd
      run: |
        cd ForestScene
        cd Build
        dir /s
            
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.visualization }}-${{ matrix.os }}-${{ matrix.targetPlatform }}
        path: ./${{ matrix.visualization }}/Build/${{ matrix.targetPlatform }}
