name: Test
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - 'master'
      - 'release'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 480
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022]
    steps:
    
    # Checkout
    - name: Checkout
      uses: actions/checkout@v3
